### ISSUE TITLE
HybridScale

### ISSUE THREAD

**Issue by ddavidovic** [razmjena/razmjena#1]
Kategorije:

- Računarstvo visokih performansi (high performance computing)
- Skalabilni algoritmi (scalable algorithms)
- Napredna linearna algebra (advanced linear algebra)
- GPU
- Hibridno računarstvo (hybrid computing)

# Grupa za skalabilno i heterogeno računarstvo visokih performansi

[OPIS GRUPE]

"Grupa za skalabilno i heterogeno računarstvo visokih performansi" (HybridScale) istraživačka je grupa nastala u sklopu uspostavnog projekta HRZZ-a "Skalabilni algoritmi visokih performansi za buduće heterogene distribuirane računalne sustave" ([HybridScale](https://pdb.irb.hr/project/irb:007326)) i dio je [Centra za informatiku i računarstvo](https://cir.com.hr/) na [Institutu Ruđer Bošković](https://www.irb.hr).

Cilj grupe je razvoj novih te unaprijeđenje postojećih računalnih metoda i algoritama linearne algebre s ciljem bržeg i učinkovitijeg izvršavanja na velikim heterogenim računalnim arhitekturama (superračunalima, hibrinim CPU-GPU računalnima). Glavni pravi istraživanja grupe su:
- povećanje skalabilnosti algoritama s obzirom na veličinu problem i količine računalnih resursa
- razvoj algoritama s minimalnom komunikacijom (engl. communication-avoiding algorithms) te optimalno korištenje kompleksnih memorijskih hijerarhija,
- razvoj modela za podešavanja hiper-parametara algoritama / softvera koje s obzirom na veličinu problema i dostupne resurse minimiziraju vrijeme izvršavanja, količinu potrebnih resursa i/ili potrošnju energije,
- primjena rezultata istraživanja u drugim područjima znanosti (računalna kemija, bioinformatika, molekularna dinimika, fizika materijala, itd) s ciljem rješavanje velikih i kompleksnih računalnih problema koje s postojećim metoda nije moguće izračunati.

## Odabrani radovi

- Alonso-Jordá, Pedro; Davidović, Davor; Sapunar, Marin; Herrero, José R.; Quintana- Ortí, Enrique S.
[Efficient update of determinants for many- electron wave function overlaps](https://www.bib.irb.hr/1098260), Computer physics communications, 258 (2021), 107521, 14 doi:10.1016/j.cpc.2020.107521
- Sapunar, Marin; Piteša, Tomislav; Davidović, Davor; Došlić, Nađa [Highly Efficient Algorithms for CIS Type Excited State Wave Function Overlaps](https://www.bib.irb.hr/1004215), Journal of chemical theory and computation, 15 (2019), 6; 3461-3469 doi:10.1021/acs.jctc.9b00235
- Aliaga, José I.; Alonso, Pedro; Badía, José M.; Chacón, Pablo; Davidović, Davor; López-Blanco, José R.; Quintana-Ortí, Enrique S.
[Fast Band--Krylov Eigensolver for Macromolecular Functional Motion Simulation on Multicore Architectures and Graphics Processors](https://www.bib.irb.hr/793409), Journal of computational physics, 309 (2016), 314-323 doi:10.1016/j.jcp.2016.01.007

## Nudimo

- Razvoj algoritama (implementacija) za GPU akceleratore: NVIDIA i AMD GPUs (NVIDIA and AMD code development),
- Prilagodba i optimizacija algoritama za distribuirane i paralelne računalne sustave (Adaptation and optimisation of the algorithms/codes for the distirbuted and parallel systems),
- Cross-platform optimizacija i razvoj portabilnih algoritama (Cross-platform portable algorithm development and optimization),
- Implementacija metoda linearne algebre za računarstvo visokih performansi (development of the high-performance linear algebra routines) 
- Savjetovanje o primjeni naprednog računarstva za efikasno rješavanje računalnih problema (Consultancy on the application of the high-performance computing for the efficient solution of computational problems).

## Tražimo

- Znanje i iskustvo u primjeni strojnog učenja za optimizaciju hiper-parametara algoritama (računalnih kodova) (Experience and knowledge in the application of Machine Learning techniques in optimisation of algorithm's hyper-parameters)

## Kontakt

- [dr.sc. Davor Davidović](davor.davidovic@irb.hr), voditelj grupe
- [Offical web-page](https://www.irb.hr/hybridscale)
- [LINKEDIN]
- [TWITTER]
- [GITHUB]

**Comment by vedranmiletic** [comment]
Fixed via cd3a9df3a903640e4b6738ac5d8feeafb122fd38.
