### ISSUE TITLE
LAF

### ISSUE THREAD

**Issue by mmanganaro** [razmjena/razmjena#2]
Kategorije:

- Fizika
- Astrofizika

# Laboratorij za astročestičnu fiziku

Laboratorij za astročestičnu fiziku (LAF) dio je [Fakulteta za fiziku Sveučilišta u Rijeci](https://www.phy.uniri.hr/hr/). Grupa se sastoji nekoliko članova i uključena je u brojne međunarodne suradnje i eksperimente. Konkretno, grupa je već mnogo godina aktivna u proučavanju događaja najviše energije koji se odvijaju u našem svemiru, domeni koja uključuje i fiziku elementarnih čestica i astrofiziku.
Laboratorij je uključen u sljedeće eksperimente:
[MAGIC](https://magic.mpp.mpg.de/) (Major Atmospheric Gamma-ray Imaging Cherenkov teleskopi)
LST-ovi (Large Sized Telescopes)
[CTA](https://www.cta-observatory.org/) (Cherenkov telescope Array)
[Zvjezdarnica Vera Rubin](https://www.lsst.org/)
[SWGO ](https://www.swgo.org/)(Southern Wide-field Gamma-ray Observatory)
[NuGrid](https://nugrid.github.io)
Grupa je također aktivna u sljedećoj COST akciji:
COST-CA18108 [QG-MM](https://qg-mm.unizar.es/) (Quantum gravity phenomenology in the multi-messenger approach)

Članovi:
Sastav: Dijana Dominis Prester, Željko Ivezić, Marina Manganaro, Saša Mićanović, Tomislav Terzić
Doktorandi: Jasmina Isaković, Karlo Mrakovčić, Lovro Pavletić, Dijana Pavlović, Mario Pecimotika, Filip Reščić, Jelena Strišković

![Image Credit: IPAC-Caltech](https://i.imgur.com/sdLVX2B.jpeg)

Image Credit: IPAC-Caltech
## Odabrani radovi

- Acciari et al., [Proton acceleration in thermonuclear nova explosions revealed by gamma rays,
Nature Astronomy](https://ui.adsabs.harvard.edu/abs/2022NatAs...6..689A/abstract), 6, p. 689-697 (2022)
doi: 10.1038/s41550-022-01640-z
- Acciari et al., [Teraelectronvolt emission from the γ-ray burst GRB 190114C](https://ui.adsabs.harvard.edu/abs/2019Natur.575..455M/abstract), Nature 575 (2019) 455-458
doi:10.1038/s41586-019-1750-x
- Aarsten et al., [Multimessenger observations of a flaring blazar coincident with high-energy neutrino IceCube-170922A](https://ui.adsabs.harvard.edu/abs/2018Sci...361.1378I/abstract), Science 361, eaat1378 (2018)
doi:10.1126/science.aat1378

## Nudimo

-Viševalne i višeglasničke studije aktivnih galaktičkih jezgri / Multiwavelenght and multimessenger studies of Active Galactic Nuclei
-Astronomija gama zraka vrlo visoke energije / Astronomy with very-high-energy gamma rays
-Potraga za tamnom materijom gama zrakama vrlo visoke energije / Dark Matter searches with very-high-energy gamma rays
-Simulacije Nuklearna astrofizika procesa / Simulacije nuklearnih astrofizičkih procesa
-Studije kršenja Lorentzove invarijancije / Lorentz invariance violation studies
-Detektori za astročestičnu fiziku / Detectors for astroparticle physics
-Simulacije pljuskova čestica u atmosferi / Simulations of showers of particles in the atmosphere
-Karakterizacija atmosfere za pokuse s astročesticama / Characterization of the atmosphere for astroparticle experiments
-Tehnike strojnog učenja, računalnog vida i napredne statistike primijenjene u astronomiji / Machine learning, computer vision and advanced statistics techniques applied to astronomy

## Tražimo

-Stručnjake za IT i programiranje za primjenu naprednih algoritama za obradu velikog broja podataka (big data science) / IT and programming experts for the application of advanced algorithms for processing a large amount of data (big data science)
-Stručnjake za rad na HPC računalima / Experts for working on HPC computers
-Računalne simulacije astrofizičkih procesa / Computer simulations of astrophysical processes

## Kontakt

- dr. sc. [Marina Manganaro](http://portal.uniri.hr/Portfelj/Index/2879), voditeljca 
- [Web stranica LAF @UniRi ](https://www.phy.uniri.hr/hr/ustroj/29-hr/ustroj/laboratoriji/1314-laboratorij-za-astrocesticnu-fiziku.html)

**Comment by vedranmiletic** [comment]
Fixed via d85af75a45985afcd2a94762245fe62825341d76.
